### ISSUE TITLE
Player thread panicked!

### ISSUE THREAD

**Issue by peteretep** [balenalabs/balena-sound#134]
The Spotify service has stopped working for me.

Here are the logs:

```
[2020-04-01T10:30:04Z ERROR librespot_playback::player] Player thread panicked!
01.04.20 10:30:07 (+0000)  spotify  [2020-04-01T10:30:07Z INFO  librespot] librespot (raspotify v0.14.0) 3672214 (2020-01-30). Built on 2020-02-16. Build ID: 7pZDdYUK
01.04.20 10:30:07 (+0000)  spotify  [2020-04-01T10:30:07Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-b-scr8.ap.spotify.com:4070"
01.04.20 10:30:07 (+0000)  spotify  [2020-04-01T10:30:07Z INFO  librespot_core::session] Authenticated as "peteretepeter" !
01.04.20 10:30:07 (+0000)  spotify  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
01.04.20 10:30:07 (+0000)  spotify  stack backtrace:
01.04.20 10:30:07 (+0000)  spotify  [2020-04-01T10:30:07Z INFO  librespot_core::session] Country: "GB"
01.04.20 10:30:07 (+0000)  spotify     0:  0x10ef3a4 - backtrace::backtrace::libunwind::trace::hb1e9954dcc6e7c1f
01.04.20 10:30:07 (+0000)  spotify                         at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
01.04.20 10:30:07 (+0000)  spotify     1:  0x10ef3a4 - backtrace::backtrace::trace_unsynchronized::h1b198a73034a9734
01.04.20 10:30:07 (+0000)  spotify                         at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
01.04.20 10:30:07 (+0000)  spotify     2:  0x10ef3a4 - std::sys_common::backtrace::_print_fmt::hf691518b63d0b79d
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/sys_common/backtrace.rs:84
01.04.20 10:30:07 (+0000)  spotify     3:  0x10ef3a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he6a16924c7e1913e
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/sys_common/backtrace.rs:61
01.04.20 10:30:07 (+0000)  spotify     4:  0x1111ca4 - core::fmt::write::hc426988e4c4119a8
01.04.20 10:30:07 (+0000)  spotify                         at src/libcore/fmt/mod.rs:1025
01.04.20 10:30:07 (+0000)  spotify     5:  0x10e9ff0 - std::io::Write::write_fmt::h34e90dde595ba7cd
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/io/mod.rs:1426
01.04.20 10:30:07 (+0000)  spotify     6:  0x10f1954 - std::sys_common::backtrace::_print::h406863a8800396cd
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/sys_common/backtrace.rs:65
01.04.20 10:30:07 (+0000)  spotify     7:  0x10f1954 - std::sys_common::backtrace::print::hec570bc9fdd6a536
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/sys_common/backtrace.rs:50
01.04.20 10:30:07 (+0000)  spotify     8:  0x10f1954 - std::panicking::default_hook::{{closure}}::hf187be78db8e291b
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/panicking.rs:193
01.04.20 10:30:07 (+0000)  spotify     9:  0x10f15b4 - std::panicking::default_hook::h9634e45fc0d61ba6
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/panicking.rs:210
01.04.20 10:30:07 (+0000)  spotify    10:  0x10f2030 - std::panicking::rust_panic_with_hook::h35923fdea5783220
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/panicking.rs:471
01.04.20 10:30:07 (+0000)  spotify    11:  0x10f1c48 - rust_begin_unwind
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/panicking.rs:375
01.04.20 10:30:07 (+0000)  spotify    12:  0x110dac0 - core::panicking::panic_fmt::hd74e307162bc16e5
01.04.20 10:30:07 (+0000)  spotify                         at src/libcore/panicking.rs:84
01.04.20 10:30:07 (+0000)  spotify    13:  0x110dbac - core::result::unwrap_failed::h36f73057b442c0eb
01.04.20 10:30:07 (+0000)  spotify                         at src/libcore/result.rs:1188
01.04.20 10:30:07 (+0000)  spotify    14:   0xcbc378 - <librespot_playback::audio_backend::pipe::StdoutSink as librespot_playback::audio_backend::Open>::open::hba99211ee8370642
01.04.20 10:30:07 (+0000)  spotify    15:   0xcd1308 - librespot_playback::audio_backend::mk_sink::hdcb616e92333a609
01.04.20 10:30:07 (+0000)  spotify    16:   0xc122e4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c6871de616d8893
01.04.20 10:30:07 (+0000)  spotify    17:   0xc0d78c - std::panicking::try::do_call::hac2a3db38490f7c2
01.04.20 10:30:07 (+0000)  spotify    18:  0x10f9220 - __rust_maybe_catch_panic
01.04.20 10:30:07 (+0000)  spotify                         at src/libpanic_unwind/lib.rs:78
01.04.20 10:30:07 (+0000)  spotify    19:   0xc2e200 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h39f2cbdbe410812b
01.04.20 10:30:07 (+0000)  spotify    20:  0x10e2790 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hc0d20dd2593d70b4
01.04.20 10:30:07 (+0000)  spotify                         at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
01.04.20 10:30:07 (+0000)  spotify    21:  0x10f83e4 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h81836ca2a42ca881
01.04.20 10:30:07 (+0000)  spotify                         at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
01.04.20 10:30:07 (+0000)  spotify    22:  0x10f83e4 - std::sys_common::thread::start_thread::hdbf450a6e252329e
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/sys_common/thread.rs:13
01.04.20 10:30:07 (+0000)  spotify    23:  0x10f83e4 - std::sys::unix::thread::Thread::new::thread_start::h5823a94baad158fb
01.04.20 10:30:07 (+0000)  spotify                         at src/libstd/sys/unix/thread.rs:80
```

**Comment by peteretep** [comment]
If I log into the container and start a new librespot process with a different name, it seems to work ok.

**Comment by peteretep** [comment]
This seems to be related to the mulitroom support. 
If I change the line in start.sh to 
`exec /usr/bin/librespot --name "$BLUETOOTH_DEVICE_NAME" --bitrate 320 --cache /var/cache/raspotify --enable-volume-normalisation --linear-volume --initial-volume=$SYSTEM_OUTPUT_VOLUME $SPOTIFY_CREDENTIALS
`
It works fine.

It's a pi3, 64bit os.

**Comment by peteretep** [comment]
sorry my bad, was using a custom docker compose file and forgot to update it.
