### ISSUE TITLE
Authentication failed with reason: BadCredentials

### ISSUE THREAD

**Issue by marrobHD** [balenalabs/balena-sound#221]
I checked the credentials are correct. I logged successfully in Spotify web.
```
16.06.20 21:40:10 (+0200) Restarting service 'spotify sha256:bb86f198ab9f0f9993df3ae89b46ce825a060ebb0b281615427dd9ebbf27078c'
16.06.20 21:40:01 (+0200)  spotify  [2020-06-16T19:40:01Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-b-g3w8.ap.spotify.com:4070"
16.06.20 21:40:01 (+0200)  spotify  thread 'main' panicked at 'Authentication failed with reason: BadCredentials', core/src/connection/mod.rs:121:21
16.06.20 21:40:01 (+0200)  spotify  stack backtrace:
16.06.20 21:40:01 (+0200)  spotify     0:   0xfd03a4 - backtrace::backtrace::libunwind::trace::hb1e9954dcc6e7c1f
16.06.20 21:40:01 (+0200)  spotify                         at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
16.06.20 21:40:01 (+0200)  spotify     1:   0xfd03a4 - backtrace::backtrace::trace_unsynchronized::h1b198a73034a9734
16.06.20 21:40:01 (+0200)  spotify                         at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
16.06.20 21:40:01 (+0200)  spotify     2:   0xfd03a4 - std::sys_common::backtrace::_print_fmt::hf691518b63d0b79d
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/sys_common/backtrace.rs:84
16.06.20 21:40:01 (+0200)  spotify     3:   0xfd03a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he6a16924c7e1913e
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/sys_common/backtrace.rs:61
16.06.20 21:40:01 (+0200)  spotify     4:   0xff2ca4 - core::fmt::write::hc426988e4c4119a8
16.06.20 21:40:01 (+0200)  spotify                         at src/libcore/fmt/mod.rs:1025
16.06.20 21:40:01 (+0200)  spotify     5:   0xfcaff0 - std::io::Write::write_fmt::h34e90dde595ba7cd
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/io/mod.rs:1426
16.06.20 21:40:01 (+0200)  spotify     6:   0xfd2954 - std::sys_common::backtrace::_print::h406863a8800396cd
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/sys_common/backtrace.rs:65
16.06.20 21:40:01 (+0200)  spotify     7:   0xfd2954 - std::sys_common::backtrace::print::hec570bc9fdd6a536
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/sys_common/backtrace.rs:50
16.06.20 21:40:01 (+0200)  spotify     8:   0xfd2954 - std::panicking::default_hook::{{closure}}::hf187be78db8e291b
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panicking.rs:193
16.06.20 21:40:01 (+0200)  spotify     9:   0xfd25b4 - std::panicking::default_hook::h9634e45fc0d61ba6
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panicking.rs:210
16.06.20 21:40:01 (+0200)  spotify    10:   0xfd3030 - std::panicking::rust_panic_with_hook::h35923fdea5783220
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panicking.rs:471
16.06.20 21:40:01 (+0200)  spotify    11:   0xfd2c48 - rust_begin_unwind
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panicking.rs:375
16.06.20 21:40:01 (+0200)  spotify    12:   0xfd2b90 - std::panicking::begin_panic_fmt::h51cd6b724a5d99ff
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panicking.rs:326
16.06.20 21:40:01 (+0200)  spotify    13:   0xc415b8 - futures::future::chain::Chain<A,B,C>::poll::h1f481a7805cebeb7
16.06.20 21:40:01 (+0200)  spotify    14:   0xc3455c - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h32723d28c7d886db
16.06.20 21:40:01 (+0200)  spotify    15:   0xc4b510 - futures::future::chain::Chain<A,B,C>::poll::he7efc480b607f8e6
16.06.20 21:40:01 (+0200)  spotify    16:   0xc8b990 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::hf7101bc4643d3a3d
16.06.20 21:40:01 (+0200)  spotify    17:   0xb06d10 - <librespot::Main as futures::future::Future>::poll::h39e6051da7010f1e
16.06.20 21:40:01 (+0200)  spotify    18:   0xaeec40 - futures::task_impl::std::set::h4e51aae067d11534
16.06.20 21:40:01 (+0200)  spotify    19:   0xb0db58 - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h621a887d6837858e
16.06.20 21:40:01 (+0200)  spotify    20:   0xaeedd0 - futures::task_impl::std::set::h63a28574c80b5637
16.06.20 21:40:01 (+0200)  spotify    21:   0xaed060 - std::thread::local::LocalKey<T>::with::hd47ca4d010c74fa6
16.06.20 21:40:01 (+0200)  spotify    22:   0xaecd90 - std::thread::local::LocalKey<T>::with::ha85a14e62c57594b
16.06.20 21:40:01 (+0200)  spotify    23:   0xaecbe8 - std::thread::local::LocalKey<T>::with::h04965b1b1c7a9048
16.06.20 21:40:01 (+0200)  spotify    24:   0xaeb3e4 - scoped_tls::ScopedKey<T>::set::hc4c1edb96d8883ef
16.06.20 21:40:01 (+0200)  spotify    25:   0xaf21a0 - tokio_core::reactor::Core::run::hffdc295949f1f25a
16.06.20 21:40:01 (+0200)  spotify    26:   0xb09de4 - librespot::main::h0ed06a728ac2479f
16.06.20 21:40:01 (+0200)  spotify    27:   0xb0b980 - std::rt::lang_start::{{closure}}::h3ecc962e3fb4564b
16.06.20 21:40:01 (+0200)  spotify    28:   0xfd2ac4 - std::rt::lang_start_internal::{{closure}}::hc02935a73664ebd0
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/rt.rs:52
16.06.20 21:40:01 (+0200)  spotify    29:   0xfd2ac4 - std::panicking::try::do_call::h9ca5184b6b3cc62d
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panicking.rs:292
16.06.20 21:40:01 (+0200)  spotify    30:   0xfda220 - __rust_maybe_catch_panic
16.06.20 21:40:01 (+0200)  spotify                         at src/libpanic_unwind/lib.rs:78
16.06.20 21:40:01 (+0200)  spotify    31:   0xfd3484 - std::panicking::try::hc53e4a11b02f3299
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panicking.rs:270
16.06.20 21:40:01 (+0200)  spotify    32:   0xfd3484 - std::panic::catch_unwind::ha972c7f8a413a94c
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/panic.rs:394
16.06.20 21:40:01 (+0200)  spotify    33:   0xfd3484 - std::rt::lang_start_internal::hdf6cc497202d2594
16.06.20 21:40:01 (+0200)  spotify                         at src/libstd/rt.rs:51
16.06.20 21:40:01 (+0200)  spotify    34:   0xb0adc4 - main
16.06.20 21:40:01 (+0200)  spotify    35: 0xf764d524 - __libc_start_main
16.06.20 21:40:10 (+0200)  spotify  Using Spotify login.
16.06.20 21:40:10 (+0200)  spotify  [2020-06-16T19:40:10Z INFO  librespot] librespot (raspotify v0.14.0) 3672214 (2020-01-30). Built on 2020-02-16. Build ID: 7pZDdYUK
```

**Comment by AlexProgrammerDE** [comment]
Same as: #131
